# Generated by Django 4.0.3 on 2022-05-23 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='header',
            field=models.CharField(default=True, max_length=50),
        ),
    ]
